apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{component-name}}
  namespace:  {{component-namespace}}
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: {{component-image}}
        name: container-image  
