apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: {{values.name}}-on-pull-request
  namespace: {{values.namespace}}
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
    pipelinesascode.tekton.dev/pipeline: "https://raw.githubusercontent.com/jduimovich/tad-bootstrap/main/pipelines/pipelines/docker-build.yaml"
    pipelinesascode.tekton.dev/task: "https://raw.githubusercontent.com/jduimovich/tad-bootstrap/main/pipelines/tasks/show-sbom.yaml"
    pipelinesascode.tekton.dev/task-1: "https://raw.githubusercontent.com/jduimovich/tad-bootstrap/main/pipelines/tasks/summary.yaml"
    pipelinesascode.tekton.dev/task-2: "https://raw.githubusercontent.com/jduimovich/tad-bootstrap/main/pipelines/tasks/init.yaml"
    pipelinesascode.tekton.dev/task-3: "https://raw.githubusercontent.com/jduimovich/tad-bootstrap/main/pipelines/tasks/git-clone.yaml"
    pipelinesascode.tekton.dev/task-4: "https://raw.githubusercontent.com/jduimovich/tad-bootstrap/main/pipelines/tasks/prefetch-dependencies.yaml"
    pipelinesascode.tekton.dev/task-5: "https://raw.githubusercontent.com/jduimovich/tad-bootstrap/main/pipelines/tasks/buildah.yaml"
    pipelinesascode.tekton.dev/task-6: "https://raw.githubusercontent.com/jduimovich/tad-bootstrap/main/pipelines/tasks/source-build.yaml"
    pipelinesascode.tekton.dev/task-7: "https://raw.githubusercontent.com/jduimovich/tad-bootstrap/main/pipelines/tasks/deprecated-image-check.yaml"
    pipelinesascode.tekton.dev/task-8: "https://raw.githubusercontent.com/jduimovich/tad-bootstrap/main/pipelines/tasks/clair-scan.yaml"
    pipelinesascode.tekton.dev/task-9: "https://raw.githubusercontent.com/jduimovich/tad-bootstrap/main/pipelines/tasks/sast-snyk-check.yaml"    
    pipelinesascode.tekton.dev/task-10: "https://raw.githubusercontent.com/jduimovich/tad-bootstrap/main/pipelines/tasks/clamav-scan.yaml"    
    pipelinesascode.tekton.dev/task-11: "https://raw.githubusercontent.com/jduimovich/tad-bootstrap/main/pipelines/tasks/sbom-json-check.yaml"    
spec: 
  params:
  - name: dockerfile
    value: {{values.dockerfileLocation}}
  - name: git-url
    value: '{{repo_url}}'
  - name: image-expires-after
    value: 5d
  - name: output-image
    value: {{values.image}}:on-pr-{{revision}}
  - name: path-context
    value: {{values.buildContext}}
  - name: revision
    value: '{{revision}}'
  pipelineRef:
    name: docker-build
  workspaces:
    - name: workspace
      volumeClaimTemplate: 
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
 