apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations: 
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: '[push]'
    pipelinesascode.tekton.dev/on-target-branch: '[main]'
  labels:
    appstudio.openshift.io/application: {{{TAB_APP}}}
    appstudio.openshift.io/component: {{{TAB_COMPONENT}}}
    pipelines.appstudio.openshift.io/type: build
  name: {{{TAB_COMPONENT}}}-on-push
  namespace: {{{TAB_NS}}}
  hack: ${{param.hack}}
spec:
  params:
  - name: dockerfile
    value: Dockerfile
  - name: git-url
    value: '{{repo_url}}'
  - name: output-image
    value: quay.io/redhat-user-workloads-stage/jduimovich-tenant/bootstrap-stub/bootstrap-stub:{{revision}}
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
   