apiVersion: route.openshift.io/v1
kind: Route
metadata:   
  annotations:   
    tad.gitops.set/weight-a: ".spec.to.weight"
    tad.gitops.get/weight-a: ".spec.to.weight"
    tad.gitops.set/weight-b: ".spec.alternateBackends[0].weight"
    tad.gitops.get/weight-b: ".spec.alternateBackends[0].weight"
  labels: 
    app.kubernetes.io/instance: {{values.name}}
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: {{values.name}} 
  name: {{values.name}}
  namespace: {{values.namespace}}
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{values.name}}-a
    weight: 99 
  alternateBackends:
  - kind: Service
    name: {{values.name}}-b
    weight: 1          
