apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: {{values.name}}
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: {{values.name}} 
  name: {{values.name}}-b
  namespace: {{values.namespace}}
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: {{values.name}}-b 
