apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: {{component-name}}
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: {{component-name}} 
  name: {{component-name}}
  namespace: {{component-namespace}}
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: {{component-name}} 
