apiVersion: route.openshift.io/v1
kind: Route
metadata:   
  annotations:   
    tad.gitops.set/service-a: ".spec.to.name"
    tad.gitops.set/weight-a: ".spec.to.weight" 
    tad.gitops.set/service-b: ".spec.alternateBackends[0].name"
    tad.gitops.set/weight-b: ".spec.alternateBackends[0].weight" 
  labels: 
    app.kubernetes.io/instance: {{values.name}}
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: {{values.name}} 
  name: {{values.name}}
  namespace: {{values.namespace}}
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{values.name}} 
    weight: 99 
  alternateBackends:
  - kind: Service
    name: {{values.name}} 
    weight: 1          
